- name: Ensuring Homebrew Is Installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
  fail:
    msg: "Homebrew is missing...Install from http://brew.sh/"
  when:
    - not homebrew_check.stat.exists
    - not install_homebrew_if_missing

- name: Installing Homebrew
  expect:
    command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    responses:
      (?i)Press RETURN/ENTER to continue or any other key to abort: "\r"
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing

- name: Updating .zshrc to include Homebrew path
  lineinfile:
    path: ~/.zshrc
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: yes
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing

- name: Apply changes to .zshrc
  command: source ~/.zshrc
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing
