- name: Download custom macOS setup script
  shell: |
    curl -o /tmp/macos.todo.sh https://raw.githubusercontent.com/sigridjineth/personal-ansibles/main/macos/macos.todo.sh
    chmod 0755 /tmp/macos.todo.sh
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
  changed_when: true

- name: Run custom macOS setup script
  shell: . /tmp/macos.todo.sh
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
  changed_when: true
  become: true