# https://github.com/geerlingguy/mac-dev-playbook/blob/master/tasks/extra-packages.yml
- name: Install global PIP packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ pip_packages }}"
