configure_dotfiles: false
configure_dock: true
# dock_dockutil_install: true
# dock_dockutil_tap: lotyp/formulae/dockutil
dock_dockitems_erase_all: true

# dockitems_remove:
#   - Launchpad
#   - Messages
#   - Mail
#   - Maps
#   - Photos
#   - FaceTime
#   - Calendar
#   - Contacts
#   - Freeform
#   - TV
#   - Podcasts
#   - 'App Store'
#   - Music
#   - Numbers
#   - Pages

dockitems_persist: []

homebrew_installed_packages:
  - ansible
  - bat # cat with syntax highlighting
  - blackhole-2ch # Record screen with internal audio
  - bun
  - ffmpeg
  - gh
  - git
  - jq
  - fnm
  - openssl
  - pnpm
  - rust
  - ssh-copy-id
  - unzip
  - wget
  - yt-dlp # Youtube CLI downloader
  - go
  - python@3.11
  - google-cloud-sdk
  - llm
  - poe
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - tmux
  - kubernetes-cli
  - kubernetes-helm
  - pipx

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - oven-sh/bun

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - arc
  - bettertouchtool
  - calibre
  - discord
  - docker
  - firefox
  - font-fira-code
  - google-chrome
  - karabiner-elements
  - keyboard-maestro
  - notion
  - obs
  - obsidian
  - postman
  - raycast
  - setapp
  - slack
  - spotify
  - visual-studio-code
  - vlc
  - warp
  - webstorm
  - zoom
  - intellij-idea
  - pycharm
  - goland
  - datagrip
  - figma
  - 1password-cli
  - iterm2
  - hpedrorodrigues/tools/dockutil # https://github.com/geerlingguy/mac-dev-playbook/issues/153

npm_packages:
  - prettier
  - eslint
  - typescript
  - ts-node

pip_packages:
  - poetry