- name: Configure host
  hosts: all

  vars_files:
    - config.yml

  # pre_tasks:
  #   - name: Include playbook configuration.
  #     include_vars: '{{ item }}'
  #     with_fileglob:
  #       - '{{ playbook_dir }}/config.yml'
  #     tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: wayofdev.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/zsh.yml
      tags: ['zsh']
    - import_tasks: tasks/nvm.yml
      tags: ['macos', 'nvm']
    - import_tasks: tasks/npm-packages.yml
      tags: ['macos', 'npm']
    - import_tasks: tasks/macos.yml
      tags: ['macos']
    - import_tasks: tasks/homebrew.yml
      tags: ['macos', 'homebrew']