---
# roles:
# - name: elliotweiser.osx-command-line-tools
# - name: geerlingguy.dotfiles

collections:
  - name: geerlingguy.mac

roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: wayofdev.dock